
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main.java;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POWER = 27;
  public static final int INCREMENT = 28;
  public static final int CHAR = 6;
  public static final int EQUALS = 34;
  public static final int CASE = 44;
  public static final int INTEGER = 3;
  public static final int GREATER = 32;
  public static final int FOR = 42;
  public static final int CONJUNCTION = 36;
  public static final int DECREMENT = 29;
  public static final int SUBSTRACTION = 23;
  public static final int END_EXPRESSION = 15;
  public static final int BOOL = 5;
  public static final int SEPARATOR = 16;
  public static final int DIFFERENT = 35;
  public static final int OPEN_BLOCK = 13;
  public static final int LESSER = 30;
  public static final int IF = 39;
  public static final int ASSIGN = 21;
  public static final int MAIN = 2;
  public static final int EOF = 0;
  public static final int RETURN = 47;
  public static final int GREATER_EQUAL = 33;
  public static final int error = 1;
  public static final int NEGATION = 38;
  public static final int DISJUNCTION = 37;
  public static final int LITERAL_CHAR = 11;
  public static final int ADD = 22;
  public static final int MODULO = 26;
  public static final int CLOSE_BRACKET = 18;
  public static final int BREAK = 46;
  public static final int OPEN_BRACKET = 17;
  public static final int LITERAL_FLOAT = 9;
  public static final int SWITCH = 43;
  public static final int OPEN_PARENTHESIS = 19;
  public static final int LITERAL_INT = 8;
  public static final int COLON = 48;
  public static final int ELSE = 40;
  public static final int CLOSE_BLOCK = 14;
  public static final int READ = 50;
  public static final int LITERAL_STRING = 12;
  public static final int WHILE = 41;
  public static final int DEFAULT = 45;
  public static final int FLOAT = 4;
  public static final int LESSER_EQUAL = 31;
  public static final int LITERAL_BOOL = 10;
  public static final int STRING = 7;
  public static final int CLOSE_PARENTHESIS = 20;
  public static final int DIVISION = 25;
  public static final int MULTIPLICATION = 24;
  public static final int PRINT = 49;
  public static final int IDENTIFIER = 51;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "INTEGER",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "LITERAL_INT",
  "LITERAL_FLOAT",
  "LITERAL_BOOL",
  "LITERAL_CHAR",
  "LITERAL_STRING",
  "OPEN_BLOCK",
  "CLOSE_BLOCK",
  "END_EXPRESSION",
  "SEPARATOR",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "OPEN_PARENTHESIS",
  "CLOSE_PARENTHESIS",
  "ASSIGN",
  "ADD",
  "SUBSTRACTION",
  "MULTIPLICATION",
  "DIVISION",
  "MODULO",
  "POWER",
  "INCREMENT",
  "DECREMENT",
  "LESSER",
  "LESSER_EQUAL",
  "GREATER",
  "GREATER_EQUAL",
  "EQUALS",
  "DIFFERENT",
  "CONJUNCTION",
  "DISJUNCTION",
  "NEGATION",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "RETURN",
  "COLON",
  "PRINT",
  "READ",
  "IDENTIFIER"
  };
}

